// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("canopy")>]
[<assembly: AssemblyProductAttribute("canopy")>]
[<assembly: AssemblyDescriptionAttribute("f# web automation and testing library, built on top of Selenium (friendly to c# also)")>]
[<assembly: AssemblyVersionAttribute("2.1.1")>]
[<assembly: AssemblyFileVersionAttribute("2.1.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "canopy"
    let [<Literal>] AssemblyProduct = "canopy"
    let [<Literal>] AssemblyDescription = "f# web automation and testing library, built on top of Selenium (friendly to c# also)"
    let [<Literal>] AssemblyVersion = "2.1.1"
    let [<Literal>] AssemblyFileVersion = "2.1.1"
    let [<Literal>] AssemblyConfiguration = "Release"
